//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinMTR.rc
//
#define IDD_WINMTR_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_STRING_SB_NAME              104
#define IDS_STRING_SB_PING              105
#define IDS_STRING_CLEAR_HISTORY        106
#define IDS_STATUS_READY                107
#define IDS_STATUS_TRACING              108
#define IDS_STATUS_STOPPING             109
#define IDS_STATUS_RESOLVING            110
#define IDS_STATUS_PUBLIC_IP_QUERYING   111
#define IDS_STATUS_PUBLIC_IP_FAILED     112
#define IDS_STATUS_PUBLIC_IP_FORMAT     113
#define IDS_ERROR_NO_HOST               114
#define IDS_ERROR_RESOLVE_FAILED        115
#define IDS_ERROR_INVALID_OPTIONS       116
#define IDS_NO_RESPONSE                 117
#define IDS_NETWORK_INFO_LOADING        118
#define IDS_NETWORK_INFO_UNAVAILABLE    119
#define IDS_NETWORK_INFO_IPV4           120
#define IDS_NETWORK_INFO_IPV6           121
#define IDS_NETWORK_INFO_ADDRESS        122
#define IDS_NETWORK_INFO_HOSTNAME       123
#define IDS_NETWORK_INFO_CITY           124
#define IDS_NETWORK_INFO_REGION         125
#define IDS_NETWORK_INFO_COUNTRY        126
#define IDS_NETWORK_INFO_ASN            127
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_OPTIONS              129
#define IDD_DIALOG_LICENSE              130
#define IDD_DIALOG_PROPERTIES           131
#define IDD_DIALOG_HELP                 132
#define IDD_DIALOG_NETWORK_INFO         135
#define IDS_NETWORK_INFO_ISP            136
#define IDS_NETWORK_INFO_DNS            137
#define IDS_NETWORK_INFO_NOT_AVAILABLE  138
#define IDS_NETWORK_INFO_DNS_RESOLVER   139
#define IDS_NETWORK_INFO_ECS            140
#define IDS_NETWORK_INFO_ECS_SUPPORTED_FORMAT 141
#define IDS_NETWORK_INFO_ECS_NOT_SUPPORTED 142
#define IDS_NETWORK_INFO_ECS_UNKNOWN    143
#define IDS_NETWORK_INFO_SOURCE         144
#define IDS_NETWORK_INFO_SOURCE_SEPARATOR 145
#define IDS_COL_HOST                    150
#define IDS_COL_HOP                     151
#define IDS_COL_LOSS                    152
#define IDS_COL_SENT                    153
#define IDS_COL_RECEIVED                154
#define IDS_COL_BEST                    155
#define IDS_COL_AVERAGE                 156
#define IDS_COL_WORST                   157
#define IDS_COL_LAST                    158
#define IDS_COL_JITTER                  159
#define IDS_COL_STDDEV                  160
#define IDS_COL_COUNTRY                 161
#define IDS_COL_ASN                     162
#define IDS_COL_ISP                     163
#define IDS_FILTER_TEXT                 164
#define IDS_FILTER_HTML                 165
#define IDS_FILTER_CSV                  166
#define IDS_FILTER_JSON                 167
#define IDS_BUTTON_START                168
#define IDS_BUTTON_STOP                 169
#define IDS_WINDOW_TITLE                170
#define IDS_NO_RESPONSE_RANGE           171
#define IDS_MENU_COPY_TEXT              172
#define IDS_MENU_COPY_HTML              173
#define IDS_MENU_EXPORT_TEXT            174
#define IDS_MENU_EXPORT_HTML            175
#define IDS_MENU_EXPORT_CSV             176
#define IDS_MENU_EXPORT_JSON            177
#define IDS_STATUS_SCREENSHOT_COPIED    178
#define IDS_STATUS_SCREENSHOT_FAILED    179
#define IDS_COMPANY_LINK                184
#define IDS_NETWORK_SUMMARY_HOSTNAME_FORMAT 185
#define IDS_NETWORK_SUMMARY_COUNTRY_FORMAT 186
#define IDS_NETWORK_SUMMARY_CITY_FORMAT 187
#define IDS_NETWORK_SUMMARY_ASN_FORMAT  188
#define IDS_NETWORK_SUMMARY_ISP_FORMAT  189
#define IDS_BUTTON_NETWORK_DETAILS      190
#define IDS_ERROR_ADDRESS_FAMILY_REQUIRED 191
#define IDS_WARNING_SHARE_INCOMPLETE    192
#define IDC_EDIT_HOST                   1000
#define IDC_LIST_MTR                    1001
#define ID_RESTART                      1002
#define ID_OPTIONS                      1003
#define IDC_EDIT_INTERVAL               1004
#define ID_CTTC                         1004
#define IDC_EDIT_SIZE                   1005
#define ID_CHTC                         1005
#define IDC_CHECK_DNS                   1006
#define ID_EXPT                         1006
#define ID_EXPH                         1007
#define ID_LICENSE                      1008
#define IDC_EDIT_LICENSE                1011
#define IDC_EDIT_PHOST                  1012
#define IDC_EDIT_PIP                    1013
#define IDC_EDIT_PSENT                  1014
#define IDC_EDIT_PRECV                  1015
#define IDC_EDIT_PLOSS                  1016
#define IDC_EDIT_PLAST                  1017
#define IDC_EDIT_PBEST                  1018
#define IDC_EDIT_PAVRG                  1019
#define IDC_EDIT_PWORST                 1020
#define IDC_EDIT_PCOMMENT               1021
#define IDC_STATICS                     1022
#define IDC_STATICJ                     1023
#define IDC_COMBO_HOST                  1024
#define IDC_EDIT_MAX_LRU                1025
#define IDC_MFCLINK1                    1026
#define IDC_EDIT_MAX_HOPS               1027
#define IDC_EDIT_TIMEOUT                1028
#define IDC_EDIT_CYCLES                 1029
#define IDC_EDIT_TOS                    1030
#define IDC_EDIT_PATTERN                1031
#define IDC_CHECK_DF                    1032
#define IDC_CHECK_ASN                   1033
#define IDC_CHECK_PUBLIC_INFO           1034
#define ID_RESET_STATS                  1036
#define ID_EXPC                         1037
#define ID_EXPJ                         1038
#define IDC_EDIT_NETWORK_INFO           1039
#define ID_COPY_NETWORK_INFO            1040
#define ID_CAPTURE_SCREENSHOT           1041
#define ID_REPORT_MENU                  1042
#define IDC_PUBLIC_IP_TEXT              1043
#define IDC_PUBLIC_HOSTNAME_TEXT        1044
#define IDC_COMPANY_LINK                1045
#define IDC_PUBLIC_COUNTRY_TEXT         1046
#define IDC_PUBLIC_ASN_TEXT             1047
#define ID_NETWORK_DETAILS              1048
#define IDC_PUBLIC_CITY_TEXT            1049
#define IDC_PUBLIC_ISP_TEXT             1050
#define ID_RESTORE_DEFAULTS             1051
#define IDC_CHECK_IPV4                  1052
#define IDC_CHECK_IPV6                  1053
#define IDC_TRACE_HOST_DISPLAY          1054
#define IDC_STATIC_ACTIONS              1055
#define IDC_EDIT_FIRST_TTL              1056
#define IDC_EDIT_DUE_TTL                1057
#define IDC_EDIT_MAX_UNKNOWN            1058
#define IDC_EDIT_MAX_DISPLAY_PATHS      1059
#define IDC_EDIT_CACHE_SECONDS          1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
